# Generated by Django 5.2.16 on 2026-07-31 18:52

import blobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link')], editable=False, max_length=8)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=blobs.models._upload_to)),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to=blobs.models._upload_to)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('site_name', models.CharField(blank=True, max_length=120)),
                ('preview_image', models.ImageField(blank=True, editable=False, upload_to=blobs.models._upload_to)),
                ('embed_url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
