# Generated by Django 5.2.16 on 2026-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blobs', '0002_sub_blobs_and_many_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='edited',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
